SiteWorkMotor/Controllers/AdministrativoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Core;
using Core.Core;
using Core.Security;
using Domain.Security;
using SiteWorkMotor.ViewModel;

namespace SiteWorkMotor.Controllers

{
    public class AdministrativoController : Controller
    {
        private readonly UsuarioCore _usuarioCore = new UsuarioCore();
        private readonly ContatoCore _contato = new ContatoCore();
        private readonly FormsAuthenticationService _authentication = new FormsAuthenticationService(System.Web.HttpContext.Current);
        // GET: Administrativo
        public ActionResult Index()
        {
            if (new UsuarioAutenticado().Usuario != null)
            {
                var contatos = _contato.TodosContatos();
                _contato.AtualizarContatosVisualizados(contatos);
                return View("Contato", contatos);

            }
            return View();
        }
        [HttpPost]
        public ActionResult Logar(UsuarioViewModel usuario)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", usuario);
            }
            if (_usuarioCore.Autenticar(usuario.Login, usuario.Senha, 1))
            {
                var u = _usuarioCore.PorLogin(usuario.Login);
                _authentication.SignIn(u, false);
                return View("Contato", _contato.TodosContatos());
            }

            @ViewBag.mensagem = "Usuário não autenticado.";
            return View("Index", usuario);

        }
        public ActionResult Logout()
        {
            Session.Abandon();
            _authentication.SignOut();
            return RedirectToAction("Index");
        }

    }


}

SiteWorkMotor/Controllers/DPKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core;
using Core.Core;
using Newtonsoft.Json;
using RestSharp;
using SiteWorkMotor.Helper;
using SiteWorkMotor.ViewModel;

namespace SiteWorkMotor.Controllers
{
    public class DPKController : Controller
    {
        // GET: DPK
        private readonly PatrocinadorCore _patrocinadorCore = new PatrocinadorCore();
        private readonly TextoHelper _textoHelpers = new TextoHelper();
        private readonly ValidacaoHelper _validacaoHelpers = new ValidacaoHelper();
        private readonly EmailFreeHelper _emailHelper = new EmailFreeHelper();
        private readonly ClienteCore _clienteCore = new ClienteCore();
        private readonly LogContatoCore _logContatoCore = new LogContatoCore();
        private readonly ExeCore _exeCore = new ExeCore();
        private readonly SolicitacaoCore _solicitacaoCore = new SolicitacaoCore();

        public ActionResult Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.todos = true;
                ViewBag.tipoAcesso = id;
                return View(new ClienteViewModel());
            }

            ViewBag.todos = false;
            ViewBag.tipoAcesso = id;
            return View(new ClienteViewModel());
        }

        [HttpPost]
        public ActionResult RegistrarCliente1(ClienteViewModel modelCliente)
        {
            var cliente = new Cliente
            {
                Email = modelCliente.Email,
                Telefone = _textoHelpers.RemoverFormatacao(modelCliente.Telefone, true),
                DataCadastro = DateTime.Now,
                CpfCnpj = "",
                NomeRazaoSocial = ""
            };
            var inseriuOk = _clienteCore.Inserir(cliente);
            if (inseriuOk)
            {
                var indicacao = new Indicacao()
                {
                    RazaoSocialNome = cliente.NomeRazaoSocial,
                    Email = cliente.Email,
                    Telefone = cliente.Telefone,
                    Data = cliente.DataCadastro,
                    StatusId = 1,
                    RepresentanteId = 10,
                    PatrocinadorId = 1
                };
                if (!_clienteCore.InserirIndicacao(indicacao)) return Content("nope");
                ModelState.Clear();
                modelCliente.Id = cliente.Id;
                modelCliente.IndicacaoId = indicacao.Id;
                modelCliente.PatrocinadorId = 1;
                _emailHelper.EnviarEmailPriCadastro(cliente);
                return PartialView("_CadastroDowload", modelCliente);
            }
            return Content("nope");
        }
        [HttpPost]
        public bool RegistrarCliente(ClienteViewModel modelCliente)
        {
            modelCliente.CpfCnpj = _textoHelpers.RemoverFormatacao(modelCliente.CpfCnpj);
            modelCliente.Telefone = _textoHelpers.RemoverFormatacao(modelCliente.Telefone, true);

            modelCliente.Cep = _textoHelpers.RemoverFormatacao(modelCliente.Cep, true);

            var cliente = new Cliente();

            var url = "http://api.postmon.com.br/v1/cep/" + modelCliente.Cep;

            try
            {
                var content = GetJson(url);
                var enderecoCliente = JsonConvert.DeserializeObject<HomeController.Postmon>(content);

                cliente.Rua = enderecoCliente.logradouro;
                cliente.Bairro = enderecoCliente.bairro;
                cliente.Cidade = enderecoCliente.cidade;
                cliente.Estado = enderecoCliente.estado;
            }
            catch (Exception e)
            {
                //ignore
            }

            cliente.CpfCnpj = modelCliente.CpfCnpj;
            cliente.NomeRazaoSocial = modelCliente.RazaoSocial;
            cliente.Email = modelCliente.Email;
            cliente.Telefone = modelCliente.Telefone;
            cliente.PatrocinadorId = modelCliente.PatrocinadorId;
            cliente.DataCadastro = DateTime.Now;
            cliente.Cep = modelCliente.Cep;
            cliente.Antigo = false;
            cliente.Upgrade = false;
            cliente.Id = modelCliente.Id;

            var indicacao = _clienteCore.IndicacaoPorId(modelCliente.IndicacaoId);
            indicacao.RazaoSocialNome = cliente.NomeRazaoSocial;
            indicacao.Email = cliente.Email;
            indicacao.Telefone = cliente.Telefone;
            indicacao.Data = cliente.DataCadastro ?? new DateTime();
            indicacao.StatusId = 1;
            indicacao.Cidade = cliente.Cidade;
            indicacao.Estado = cliente.Estado;
            indicacao.RepresentanteId = 10;
            _clienteCore.AtualizaIndicacao(indicacao);

            var resp = NotificarApi(cliente);

            if (resp)
            {
                var inseriuOk = _clienteCore.Atualiza(cliente);
                if (inseriuOk)
                {
                    var patrocinador = _patrocinadorCore.RetornarPorId(cliente.PatrocinadorId);
                    return true;
                }
            }
            _emailHelper.EnviarEmailSegCadastro(cliente, _patrocinadorCore.RetornarPorId(4));
            return false;
        }

        public FileResult BaixarArquivo(int idPatrocinador)
        {
            var exe = _exeCore.RetornarExePorIdPatrocinador(idPatrocinador);
            return File(exe.Link, "application/exe", exe.Nome);
        }

        public FileResult BaixarAtualizador(string descPatrocinador)
        {
            var idPatrocinador = _patrocinadorCore.RetornarPorDescricao(descPatrocinador).Id;
            var exe = _exeCore.RetornarAtualizadorPorIdPatrocinador(idPatrocinador);
            return File(exe.Link, "application/exe", exe.Nome);
        }

        public bool NotificarApi(Cliente cli)
        {
            var personString = "<FREE><CNPJ>" + cli.CpfCnpj + "</CNPJ><RZSOCIAL>" + cli.NomeRazaoSocial +
                               "</RZSOCIAL><TELEFONE>" + cli.Telefone + "</TELEFONE><EMAIL>" + cli.Email +
                               "</EMAIL><BAIRRO>" + cli.Bairro + "</BAIRRO><ENDERECO>" + cli.Rua +
                               "</ENDERECO><CIDADE>" + cli.Cidade + "</CIDADE><ESTADO>" + cli.Estado + "</ESTADO></FREE>";

            var restClient = new RestClient("http://201.77.177.42/QueridoCarro/aFreeGravaOficina.aspx");

            var restRequest = new RestRequest("Post", Method.POST) { RequestFormat = DataFormat.Xml };

            restRequest.AddParameter("application/xml", personString, ParameterType.RequestBody);
            var response = restClient.Execute(restRequest);

            return response.StatusCode.Equals(HttpStatusCode.OK);
        }

        public ActionResult Patrocinadores(string msgRetorno)
        {
            if (string.IsNullOrEmpty(msgRetorno))
            {
                ViewBag.todos = true;
                return View();
            }
            else
            {
                if (msgRetorno.Equals("error"))
                {
                    ViewBag.EmailContatoErro = "Erro no envio de contato.";
                }
                else if (msgRetorno.Equals("sucesso"))
                {
                    ViewBag.EmailContatoSucesso1 = "Contato enviado com sucesso !";
                    ViewBag.EmailContatoSucesso2 = "Em breve entraremos em contato com você.";
                }

                ViewBag.todos = true;
                return View();
            }
        }

        [HttpPost]
        public ActionResult ContatoPatrocinador(ContatoPatrocinadorViewModel contato)
        {
            var cont = new LogContatoPatrocinador()
            {
                NomeRazaoSocial = contato.NomeRazaoSocial,
                Email = contato.Email,
                Telefone = contato.Telefone,
                Mensagem = contato.Mensagem,
                Data = DateTime.Now
            };

            _logContatoCore.Inserir(cont);

            var retorno = _emailHelper.EnviarEmailContato(cont) ? "sucesso" : "erro";

            return RedirectToAction("Index", "Parceiros", new { msgRetorno = retorno });
        }

        public ActionResult Suporte(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.Atualizador = false;
                ViewBag.todos = true;
                ViewBag.tipoAcesso = id;
                return View();
            }

            var pat = _patrocinadorCore.RetornarPorDescricao(id);
            var atualizador = _exeCore.RetornarAtualizadorPorIdPatrocinador(pat.Id);

            if (atualizador == null)
            {
                ViewBag.Atualizador = false;
                ViewBag.todos = false;
                ViewBag.tipoAcesso = id;
                return View();
            }

            ViewBag.DataAtualizador = atualizador.Data;
            ViewBag.Atualizador = true;
            ViewBag.todos = false;
            ViewBag.tipoAcesso = id;
            return View();
        }

        public ActionResult Upgrade(string id)
        {
            var cliente = _clienteCore.RetornarPorCpfCnpj(id);

            if (cliente != null)
            {
                var pat = _patrocinadorCore.RetornarPorId(cliente.PatrocinadorId);

                var sol = new Solicitacao()
                {
                    ClienteId = cliente.Id,
                    TipoId = 1,
                    Data = DateTime.Now,
                    StatusId = 1
                };
                _solicitacaoCore.Inserir(sol);

                _emailHelper.EnviarEmailUpgrade(cliente, pat);

                ViewBag.todos = true;
                ViewBag.Registrar = false;
            }
            else
            {
                ViewBag.Patrocinadores = new SelectList(_patrocinadorCore.RetornarTodos(), "Id", "NomeFantasia");
                ViewBag.todos = true;
                ViewBag.Registrar = true;

SiteWorkMotor/Views/Shared/_FormExit.cshtml
@using SiteWorkMotor.ViewModel
@model SiteWorkMotor.ViewModel.ClienteViewModel

<div class="container">
    @using (Html.BeginForm("RegistrarCliente", "Free", FormMethod.Post, new { @id = "form-registrar-cliente-free", role = "form", @class = "form-group fonttt" }))
    {
        <div class="col-md-12 col-sm-12">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control form-group", @type = "email", @placeholder = "E-MAIL", @required = "required", @id = "formEmail" })
            @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-12 col-sm-12">
            @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control form-group", @id = "telefone", @placeholder = "DDD+TELEFONE", @required = "required" })
            @Html.ValidationMessageFor(x => x.Telefone, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-2 col-md-offset-10">
            <button type="submit" id="btn-enviar" class="btn btn-default formHome"><b>AVANÇAR</b> <i class="fa"></i></button>
        </div>
    }
</div>

<script>

    $("#step-two").on('hidden.bs.modal',
        function (e) {
            $("#btn-enviar i").removeClass("fa-spin").removeClass("fa-spinner");
            $("#btn-enviar").prop("disabled", false);
        }
    );

    $(document).ready(function() {
        $("#cep").mask("99999-999");
    });

    
</script>

SiteWorkMotor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window,document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '2301367826785231'); 
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" 
             src="https://www.facebook.com/tr?id=2301367826785231&ev=PageView
&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

</head>
<body class="imagemlogin">


<section class="wrapper site-min-height">
    @RenderBody()
    <div id="modal"></div>
</section>

@RenderSection("scripts", required: false)

</body>
</html>

SiteWorkMotor/Views/Shared/_LayoutAdm.cshtml
@using Domain.Security
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/landingpage")
</head>
<body class="layoutMenu">

    <nav class="navbar navbar-info navbar-fixed-top">
            <img class="img-responsive logolayoutadm" src="/Content/Imagens/logoMenu.png"  alt=""/>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Icones">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
     
        </div>
        <div class="collapse navbar-collapse " id="Icones">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("Logout", "Administrativo", new {area = ""})">Sair</a></li>
             
            </ul>
        </div>
    </nav>

    <aside>
        <div id="sidebar" class="nav-collapse ">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a href="@Url.Action("Index", "Administrativo", new {area = ""})">

                        <span>Contatos</span>
                    </a>
                </li>

            </ul>
        </div>
   
    </aside>
    <section id="main-content">
        <section class="wrapper site-min-height">
            @RenderBody()
            <div id="modal"></div>
        </section>
    </section>

    @RenderSection("scripts", required: false)

    <script>
        cxl.menu();
        /*---LEFT BAR ACCORDION----*/
        $(function () {
            $('#nav-accordion').dcAccordion({
                eventType: 'click',
                autoClose: true,
                saveState: true,
                disableLink: true,
                speed: 'slow',
                showCount: false,
                autoExpand: true,
                //        cookie: 'dcjq-accordion-1',
                classExpand: 'dcjq-current-parent'
            });
        });

        var Script = function () {

            $("#sidebar").niceScroll({
                styler: "fb",
                cursorcolor: "#e8403f",
                cursorwidth: '3',
                cursorborderradius: '10px',
                background: '#404040',
                spacebarenabled: false,
                cursorborder: ''
            });
            $("html").niceScroll({
                styler: "fb",
                cursorcolor: "#e8403f",
                cursorwidth: '6',
                cursorborderradius: '10px',
                background: '#404040',
                spacebarenabled: false,
                cursorborder: '',
                zindex: '1000'
            });
            jQuery('.panel .tools .fa-chevron-down').click(function () {
                var el = jQuery(this).parents(".panel").children(".panel-body");
                if (jQuery(this).hasClass("fa-chevron-down")) {
                    jQuery(this).removeClass("fa-chevron-down").addClass("fa-chevron-up");
                    el.slideUp(200);
                } else {
                    jQuery(this).removeClass("fa-chevron-up").addClass("fa-chevron-down");
                    el.slideDown(200);
                }
            });
            jQuery('.panel .tools .fa-times').click(function () {
                jQuery(this).parents(".panel").parent().remove();
            });

            if ($(".custom-bar-chart")) {
                $(".bar").each(function () {
                    var i = $(this).find(".value").html();
                    $(this).find(".value").html("");
                    $(this).find(".value").animate({
                        height: i
                    },
                        2000)
                })
            }
        }();
        $('[data-toggle="tooltip"]').tooltip();


    </script>
</body>
</html>

SiteWorkMotor/Views/Shared/_LayoutClear.cshtml
<!DOCTYPE html>
<html>
<head>
    <link class="fundoverde" rel="icon" type="imagem/png" href="~/Content/Imagens/money.png" />

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")

</head>
<body class="telalogin">
<img src="~/Content/Imagens/banner-promo1.png" style ="    margin-bottom: -16px;"class="img-responsive banner hidden-sm hidden-xs" alt="" />
<section class="wrapper site-min-height">
    @RenderBody()
    <div id="modal"></div>
</section>

@RenderSection("scripts", required: false)

</body>
</html>

SiteWorkMotor/Views/Shared/_LayoutDPK.cshtml
@using System.Runtime.InteropServices.ComTypes
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
    <script type="text/javascript" async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/66e1e82b-3ccf-45ce-9486-02d45580fa82-loader.js"></script>
    <title>@ViewBag.Title</title>
    @Scripts.RenderFormat("<script src='{0}' async></script>", "~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/landingpage")
    @Styles.Render("~/Content/cssmainDPK")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="logodpk" href="@Url.Action("Index","DPK")">
                </a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>

    <div class="container ">
        @RenderBody()
    </div>
<script>
    jQuery("#Telefone").mask("(99) 99999-9999").focusout(function (event) {
        var target, phone, element;
        target = (event.currentTarget) ? event.currentTarget : event.srcElement;
        phone = target.value.replace(/\D/g, '');
        element = $(target);
        element.unmask();
        if (phone.length <= 10) {
            element.mask("(99) 9999-9999");
        } else {
            element.mask("(99) 99999-9999");
        }
    });

    workFree.mascararContato();
    workFree.mascararCpfCnpj();

    $(document).ready(function() {
        $("#cep").mask("99999-999");
    });
    $("#form-registrar-cliente1").submit(function(e) {
        e.preventDefault();
        $("#btn-enviar i").addClass("fa-spin").addClass("fa-spinner");
        if ($(this).valid()) {
            $.ajax({
                url: "@Url.Action("RegistrarCliente1", "DPK")",
                type: "post",
                async: true,
                data: $(this).serialize(),
                beforeSend: function() {
                },
                success: function(data) {
                    if (data != "nope") {
                        $("#form-registrar-cliente1").fadeOut(500,
                            function() {
                                $(".form-cliente").html(data);
                            });
                    }
                }
            });
        } else {
            $("#btn-enviar i").removeClass("fa-spin fa-spinner");
        }
        return false;
    });

    var cbpAnimatedHeader = (function () {

        var docElem = document.documentElement,
            header = document.querySelector('.navbar-default'),
            didScroll = false,
            changeHeaderOn = 100;

        function init() {
            window.addEventListener('scroll', function (event) {
                if (!didScroll) {
                    didScroll = true;
                    setTimeout(scrollPage, 250);
                }
            }, false);
        }

        function scrollPage() {
            var sy = scrollY();
            if (sy >= changeHeaderOn) {
                $(header).addClass('navbar-shrink');
            }
            else {
                $(header).removeClass('navbar-shrink');
            }
            didScroll = false;
        }

        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }

        init();

    })();
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments);
            },
            i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m);
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-69638641-1', 'auto');
    ga('send', 'pageview', 'event', 'botão', 'clique');
</script>


</body>
</html>

SiteWorkMotor/Views/Shared/_LayoutDrMacete.cshtml
@using System.Runtime.InteropServices.ComTypes
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
    <title>@ViewBag.Title</title>
    @Scripts.RenderFormat("<script src='{0}' async></script>", "~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/landingpage")
    @Styles.Render("~/Content/cssmainDrMacete")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <a class="link-logo-main" href="@Url.Action("Index","DrMacete")">
                        <div class="div-logo-main"></div>
                    </a>
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav navbar-right">
                    <li class="liMenu">
                        <a href="/DrMacete/Suporte/">
                            <span>Suporte</span>
                        </a>
                    </li>
                </ul>*@
            </div>
        </div>
    </div>

    <div class="container ">
        @RenderBody()
    </div>
<script>
    jQuery("#Telefone").mask("(99) 99999-9999").focusout(function (event) {
        var target, phone, element;
        target = (event.currentTarget) ? event.currentTarget : event.srcElement;
        phone = target.value.replace(/\D/g, '');
        element = $(target);
        element.unmask();
        if (phone.length <= 10) {
            element.mask("(99) 9999-9999");
        } else {
            element.mask("(99) 99999-9999");
        }
    });

    workFree.mascararContato();
    workFree.mascararCpfCnpj();

    $(document).ready(function() {
        $("#cep").mask("99999-999");
    });
    $("#form-registrar-cliente1").submit(function(e) {
        e.preventDefault();
        $("#btn-enviar i").addClass("fa-spin").addClass("fa-spinner");
        if ($(this).valid()) {
            $.ajax({
                url: "@Url.Action("RegistrarCliente1", "DrMacete")",
                type: "post",
                async: true,
                data: $(this).serialize(),
                beforeSend: function() {
                },
                success: function(data) {
                    if (data != "nope") {
                        $("#form-registrar-cliente1").fadeOut(500,
                            function() {
                                $(".form-cliente").html(data);
                            });
                    }
                }
            });
        } else {
            $("#btn-enviar i").removeClass("fa-spin fa-spinner");
        }
        return false;
    });

    var cbpAnimatedHeader = (function() {

        var docElem = document.documentElement,
            header = document.querySelector( '.navbar-default' ),
            didScroll = false,
            changeHeaderOn = 100;

        function init() {
            window.addEventListener( 'scroll', function( event ) {
                if( !didScroll ) {
                    didScroll = true;
                    setTimeout( scrollPage, 250 );
                }
            }, false );
        }

        function scrollPage() {
            var sy = scrollY();
            if ( sy >= changeHeaderOn ) {
                $(header).addClass('navbar-shrink');
            }
            else {
                $(header).removeClass('navbar-shrink' );
            }
            didScroll = false;
        }

        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }

        init();

    })();
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments);
            },
            i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m);
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-69638641-1', 'auto');
    ga('send', 'pageview','event', 'botão', 'clique');
</script>


</body>
</html>