SiteWorkMotor/Areas/Conteudo/Controllers/LoginConteudoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Core;
using Core.Security;
using Domain.Security;
using SiteWorkMotor.ViewModel;

namespace SiteWorkMotor.Areas.Conteudo.Controllers
{
    public class LoginConteudoController : Controller
    {
        private readonly UsuarioCore _usuarioCore = new UsuarioCore();
        private readonly FormsAuthenticationService _authentication = new FormsAuthenticationService(System.Web.HttpContext.Current);

        public ActionResult Index()
        {
            if (new UsuarioAutenticado().Usuario != null) return RedirectToAction("Index", "DashboardPublicacoes", new { area = "Conteudo" });
            return View();
        }

        [HttpPost]
        public ActionResult Index(UsuarioViewModel usuario)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", usuario);
            }
            if (_usuarioCore.Autenticar(usuario.Login, usuario.Senha,2))
            {
                var u = _usuarioCore.PorLogin(usuario.Login);
                _authentication.SignIn(u, false);
                return RedirectToAction("Index", "DashboardPublicacoes");
            }
            @ViewBag.mensagem = "Usuário não autenticado.";
            return View("Index", usuario);
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            _authentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

SiteWorkMotor/Areas/Conteudo/Views/LoginConteudo/Index.cshtml
@model SiteWorkMotor.ViewModel.UsuarioViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-6 bordalogin ">
            <div class="card card-signup " style="margin-top: 45px;">
                @using (Html.BeginForm("Index", "LoginConteudo", FormMethod.Post, new { @class = "form-group col-md-12" }))
                {
                    <img src="~/Content/Imagens/logoLogin.png" class="img-responsive margimbottom" alt="" />
                    <div class="content">
                        <div class="input-group col-md-12">
                            <div class="form-group label-floating" id="div-login">
                                @Html.LabelFor(x => x.Login, new { @class = "control-label" })
                                @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
                                <span class="form-control-feedback">
                                    @Html.ValidationMessageFor(x => x.Login, "", new { @class = "text-danger" })
                                </span>
                            </div>


                        </div>
                        <div class="input-group col-md-12">

                            <div class="form-group label-floating ">
                                <label class="control-label">Senha</label>
                                @Html.TextBoxFor(x => x.Senha, new { @class = "form-control", type = "password" })
                                <span class="form-control-feedback">
                                    @Html.ValidationMessageFor(x => x.Senha, "", new { @class = "text-danger" })

                                </span>
                            </div>
                        </div>
                        <div class="text-center text-danger" id="mensagemErro">
                            @if (!string.IsNullOrEmpty(ViewBag.mensagem))
                            {
                                @ViewBag.mensagem
                            }
                        </div>
                        <div class="footer text-center ">
                            <button type="submit" id="btn-logar" class="btn btn-primary btn-lg col-md-12 botaoentrar">Entrar</button>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>