SiteWorkMotor/Controllers/ParceirosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteWorkMotor.Controllers
{
    public class ParceirosController : Controller
    {
        // GET: Parceiros
        public ActionResult Index()
        {
            return View();
        }
    }
}

SiteWorkMotor/Controllers/WorkMotoPecasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Core;
using Core.Core;
using Newtonsoft.Json;
using RestSharp;
using SiteWorkMotor.Controllers;
using SiteWorkMotor.Helper;
using SiteWorkMotor.ViewModel;

namespace SiteWorkMotor.Controllers
{
    public class WorkMotoPecasController : Controller
    {
        // GET: DrMacete
        private readonly PatrocinadorCore _patrocinadorCore = new PatrocinadorCore();
        private readonly TextoHelper _textoHelpers = new TextoHelper();
        private readonly ValidacaoHelper _validacaoHelpers = new ValidacaoHelper();
        private readonly EmailFreeHelper _emailHelper = new EmailFreeHelper();
        private readonly GeradorChaveHelper _geradorChaveHelper = new GeradorChaveHelper();
        private readonly ClienteCore _clienteCore = new ClienteCore();
        private readonly LogContatoCore _logContatoCore = new LogContatoCore();
        private readonly ExeCore _exeCore = new ExeCore();
        private readonly SolicitacaoCore _solicitacaoCore = new SolicitacaoCore();

        public ActionResult Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                //ViewBag.Patrocinadores = new SelectList(_patrocinadorCore.RetornarTodos(), "Id", "NomeFantasia");
                ViewBag.todos = true;
                ViewBag.tipoAcesso = id;
                return View(new ClienteViewModel());
            }

            ViewBag.todos = false;
            ViewBag.tipoAcesso = id;
            //ViewBag.Patrocinadores = new SelectList(_patrocinadorCore.RetornarPorDescricaoList(id), "Id", "NomeFantasia");
            return View(new ClienteViewModel());
        }

        [HttpPost]
        public ActionResult RegistrarCliente1(ClienteViewModel modelCliente)
        {
            var cliente = new Cliente
            {
                Email = modelCliente.Email,
                Telefone = _textoHelpers.RemoverFormatacao(modelCliente.Telefone, true),
                DataCadastro = DateTime.Now,
                CpfCnpj = "",
                NomeRazaoSocial = ""
            };
            var inseriuOk = _clienteCore.Inserir(cliente);
            if (inseriuOk)
            {
                var indicacao = new Indicacao()
                {
                    RazaoSocialNome = cliente.NomeRazaoSocial,
                    Email = cliente.Email,
                    Telefone = cliente.Telefone,
                    Data = cliente.DataCadastro,
                    StatusId = 1,
                    RepresentanteId = 10,
                    PatrocinadorId = 9
                };
                if (!_clienteCore.InserirIndicacao(indicacao)) return Content("nope");
                ModelState.Clear();
                modelCliente.Id = cliente.Id;
                modelCliente.IndicacaoId = indicacao.Id;
                modelCliente.PatrocinadorId = 9;
                _emailHelper.EnviarEmailPriCadastro(cliente);
                return PartialView("_CadastroDowload", modelCliente);
            }
            return Content("nope");
        }
        [HttpPost]
        public bool RegistrarCliente(ClienteViewModel modelCliente)
        {
            modelCliente.CpfCnpj = _textoHelpers.RemoverFormatacao(modelCliente.CpfCnpj);

            modelCliente.Cep = _textoHelpers.RemoverFormatacao(modelCliente.Cep, true);

            var cliente = new Cliente();

            var url = "http://api.postmon.com.br/v1/cep/" + modelCliente.Cep;

            try
            {
                var content = GetJson(url);
                var enderecoCliente = JsonConvert.DeserializeObject<HomeController.Postmon>(content);

                cliente.Rua = enderecoCliente.logradouro;
                cliente.Bairro = enderecoCliente.bairro;
                cliente.Cidade = enderecoCliente.cidade;
                cliente.Estado = enderecoCliente.estado;
            }
            catch (Exception e)
            {
                //ignore
            }

            cliente.CpfCnpj = modelCliente.CpfCnpj;
            cliente.NomeRazaoSocial = modelCliente.RazaoSocial;
            cliente.Email = modelCliente.Email;
            cliente.Telefone = _textoHelpers.RemoverFormatacao(modelCliente.Telefone, true);
            cliente.PatrocinadorId = modelCliente.PatrocinadorId;
            cliente.DataCadastro = DateTime.Now;
            cliente.Cep = modelCliente.Cep;
            cliente.Antigo = false;
            cliente.Upgrade = false;
            cliente.Id = modelCliente.Id;

            //var existeCliente = _clienteCore.ExisteCliente(cliente.CpfCnpj, cliente.PatrocinadorId);

            //if (existeCliente != null)
            //{
            var indicacao = _clienteCore.IndicacaoPorId(modelCliente.IndicacaoId);
            indicacao.RazaoSocialNome = cliente.NomeRazaoSocial;
            indicacao.Email = cliente.Email;
            indicacao.Telefone = cliente.Telefone;
            indicacao.Data = cliente.DataCadastro ?? new DateTime();
            indicacao.StatusId = 1;
            indicacao.Cidade = cliente.Cidade;
            indicacao.Estado = cliente.Estado;
            indicacao.RepresentanteId = 10;
            _clienteCore.AtualizaIndicacao(indicacao);

            var resp = NotificarApi(cliente);

            if (resp)
            {
                var inseriuOk = _clienteCore.Atualiza(cliente);
                if (inseriuOk)
                {
                    var patrocinador = _patrocinadorCore.RetornarPorId(cliente.PatrocinadorId);
                    //_emailHelper.EnviarEmailSegCadastro(cliente, patrocinador);
                    //_emailHelper.EnviarEmailCadastro(cliente, patrocinador);
                    return true;
                }
            }
            //}
            //else
            //{
            //    var patrocinador = _patrocinadorCore.RetornarPorId(existeCliente.PatrocinadorId);
            _emailHelper.EnviarEmailSegCadastro(cliente, _patrocinadorCore.RetornarPorId(4));
            //    //_emailHelper.EnviarEmailCadastro(existeCliente, patrocinador);
            //    return true;
            //}
            return false;
        }

        public FileResult BaixarArquivo(int idPatrocinador)
        {
            var exe = _exeCore.RetornarExePorIdPatrocinador(idPatrocinador);
            return File(exe.Link, "application/exe", exe.Nome);
        }

        public FileResult BaixarAtualizador(string descPatrocinador)
        {
            var idPatrocinador = _patrocinadorCore.RetornarPorDescricao(descPatrocinador).Id;
            var exe = _exeCore.RetornarAtualizadorPorIdPatrocinador(idPatrocinador);
            return File(exe.Link, "application/exe", exe.Nome);
        }

        public bool NotificarApi(Cliente cli)
        {
            var personString = "<FREE><CNPJ>" + cli.CpfCnpj + "</CNPJ><RZSOCIAL>" + cli.NomeRazaoSocial +
                               "</RZSOCIAL><TELEFONE>" + cli.Telefone + "</TELEFONE><EMAIL>" + cli.Email +
                               "</EMAIL><BAIRRO>" + cli.Bairro + "</BAIRRO><ENDERECO>" + cli.Rua +
                               "</ENDERECO><CIDADE>" + cli.Cidade + "</CIDADE><ESTADO>" + cli.Estado + "</ESTADO></FREE>";

            var restClient = new RestClient("http://201.77.177.42/QueridoCarro/aFreeGravaOficina.aspx");

            var restRequest = new RestRequest("Post", Method.POST) { RequestFormat = DataFormat.Xml };

            restRequest.AddParameter("application/xml", personString, ParameterType.RequestBody);
            var response = restClient.Execute(restRequest);

            return response.StatusCode.Equals(HttpStatusCode.OK);
        }

        public ActionResult Patrocinadores(string msgRetorno)
        {
            if (string.IsNullOrEmpty(msgRetorno))
            {
                ViewBag.todos = true;
                return View();
            }
            else
            {
                if (msgRetorno.Equals("error"))
                {
                    ViewBag.EmailContatoErro = "Erro no envio de contato.";
                }
                else if (msgRetorno.Equals("sucesso"))
                {
                    ViewBag.EmailContatoSucesso1 = "Contato enviado com sucesso !";
                    ViewBag.EmailContatoSucesso2 = "Em breve entraremos em contato com você.";
                }

                ViewBag.todos = true;
                return View();
            }
        }

        [HttpPost]
        public ActionResult ContatoPatrocinador(ContatoPatrocinadorViewModel contato)
        {
            var cont = new LogContatoPatrocinador()
            {
                NomeRazaoSocial = contato.NomeRazaoSocial,
                Email = contato.Email,
                Telefone = contato.Telefone,
                Mensagem = contato.Mensagem,
                Data = DateTime.Now
            };

            _logContatoCore.Inserir(cont);

            var retorno = _emailHelper.EnviarEmailContato(cont) ? "sucesso" : "erro";

            return RedirectToAction("Patrocinadores", "WorkMotoPecas", new { msgRetorno = retorno });
        }

        public ActionResult Suporte(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.Atualizador = false;
                ViewBag.todos = true;
                ViewBag.tipoAcesso = id;
                return View();
            }

            var pat = _patrocinadorCore.RetornarPorDescricao(id);
            var atualizador = _exeCore.RetornarAtualizadorPorIdPatrocinador(pat.Id);

            if (atualizador == null)
            {
                ViewBag.Atualizador = false;
                ViewBag.todos = false;
                ViewBag.tipoAcesso = id;
                return View();
            }

            ViewBag.DataAtualizador = atualizador.Data;
            ViewBag.Atualizador = true;
            ViewBag.todos = false;
            ViewBag.tipoAcesso = id;
            return View();

SiteWorkMotor/Views/WorkMotoPecas/ConfirmacaoCadastroCliente.cshtml
@{
    ViewBag.Title = "ConfirmacaoCadastroCliente";
    Layout = "../Shared/_LayoutDrMacete.cshtml";

}

<h2>Confirmacão de Cadastro</h2>
<hr/>

<h4>Cadastro confirmado com sucesso, download em andamento ...</h4>

SiteWorkMotor/Views/WorkMotoPecas/Index.cshtml
@model SiteWorkMotor.ViewModel.ClienteViewModel
@{
    ViewBag.Title = "Workmotor Free";
    Layout = "../Shared/_LayoutMotoPecas.cshtml";
}

<div class="row div-index">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-3">
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                <iframe width="480" height="290" src="https://www.youtube.com/embed/XfiuwBjtHcA" frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="col-md-8 col-md-offset-1 div-standard-background">
                <h3 class="titulo">O MELHOR SOFTWARE DE OFICINAS <br />E AUTOPEÇAS GRATUITAMENTE</h3>
                <img class="planodpk" width="90%" src="/Content/Imagens/plano.png"/>
                
            </div>
            <br/>

            <div class="col-md-offset-8 col-md-4 form-cliente" style="margin-left: 70%; margin-top: -3%;">
                <h4 class="pull-right titulo-baixar" >BAIXE AGORA</h4>
                @using (Html.BeginForm("RegistrarCliente1", "WorkMotoPecas", FormMethod.Post, new {@id = "form-registrar-cliente1", @class = "form-horizontal", role = "form"}))
                {
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Email, new {@class = "form-control", @type = "email", @placeholder = "E-MAIL", @required = "required"})
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Telefone, new {@class = "form-control", @id = "Telefone", @placeholder = "DDD+TELEFONE", @required = "required"})
                        </div>
                        @Html.ValidationMessageFor(x => x.Telefone, "", new {@class = "text-danger"})
                    </div>
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-2  pull-right">
                            <button type="submit" id="btn-enviar" class="btn btn-danger form-control"><b>BAIXAR</b> <i class="fa"></i></button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SiteWorkMotor/Views/WorkMotoPecas/Patrocinadores.cshtml
@model SiteWorkMotor.ViewModel.ContatoPatrocinadorViewModel

@{
    ViewBag.Title = "Patrocinadores";
    Layout = "../Shared/_LayoutDPK.cshtml";


}


<div class="row div-patrocinadores">
    <div class="col-md-4 col-md-offset-1" style="margin-top: 1vw;">
        <h5>Deseja ser um patrocinador do Workmotor Free?</h5>
        <h5>Preencha o formulario que entraremos em contato com você!</h5>
    </div>
    <div class="col-md-1 "></div> 
    <div class="col-md-6 ">
        <h2>Patrocinadores</h2>
        <hr/>
    </div>   


<div class="row">
    <div class="col-md-12">
        <div class="col-md-4 col-md-offset-1 form-contato-padrocinador">
            <div class="col-md-10">
                   
            </div>

            @using (Html.BeginForm("Index", "Parceiros", FormMethod.Post, new { @class = "form-horizontal", @id = "form-contato", role = "form" }))
            {
                <div class="col-md-10">
                    @Html.ValidationSummary()
                </div>

                <div class="col-md-10 sucessContato">
                    <span>@ViewBag.EmailContatoSucesso1</span>
                </div>
                <div class="col-md-10 sucessContato">
                    <span>@ViewBag.EmailContatoSucesso2</span>
                </div>
                    
                <div class="col-md-10 errorContato">
                    <span>@ViewBag.EmailContatoErro</span>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NomeRazaoSocial, new { @class = "form-control", @placeholder = "NOME" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "E-MAIL" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control", @id="telefone", @placeholder = "TELEFONE" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Mensagem, new { @class = "form-control input-contato-mensagem", required = string.Empty, @placeholder = "MENSAGEM" })
                    </div>
                </div>

                <div class="col-md-8 col-md-offset-1">
                    <input type="submit" value="Enviar" class="btn btn-primary form-control"/>
                </div>
            }
        </div>
        <div class="col-md-1 "></div> 
            
        <div class="col-md-6 div-conteudo-patrocinadores">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    @*<div class="item active">
                        <img width="250" height="250" src="../../Content/images/logo-compredireto.png" class="img-responsive img-rounded" alt="Compre Direto">
                        <br />
                        <p style="margin-left: -12vw;">
                            No Compre Direto você encontra desde peças originais
                            até as recomendadas e homologadas pelas montadoras,além de autopeças de reposição.
                            São peças mecânicas, elétricas, de acabamento, acessórios, lubrificantes e fluídos,
                            peças de funilaria/lanternagem e milhares de produtos ligados ao universo automotivo.
                        </p>
                        <p style="margin-left: -12vw;">
                            Para mais informações, acesse: <a href="http://www.compredireto.com.br" target="_blanc">www.compredireto.com.br</a>
                        </p>
                    </div>*@
                    <div class="item" id="divdpk">
                        <img width="250" height="250" src="../../Content/images/logo-dpk.png" class="img-responsive img-rounded" alt="DPK">
                        <br />
                        <p style="margin-left: -12vw;">
                            A DPK é uma empresa que pertence ao Grupo DPaschoal especializada na distribuição
                            automotiva para todo o território nacional, conta com o mais avançado sistema de
                            distribuição com dezoito depósitos espalhados pelo País. Para realizar o atendimento,
                            possui área comercial em Campinas-SP e estruturas de Distribuição em vários estados
                            brasileiros.
                        </p>
                        <p style="margin-left: -12vw;">
                            Para mais informações, acesse: <a href="http://www.dpk.com.br" target="_blanc">www.dpk.com.br</a>
                        </p>
                    </div>

                    <div class="item " id="divgimenes">
                        <img width="250" height="250" src="../../Content/images/logo-gimenes.png" class="img-responsive img-rounded" alt="Gimenes">
                        <br />
                        <p style="margin-left: -12vw;">
                            A Gimenes é uma distribuidora de autopeças, que sempre busca ampliar sua linha de produtos
                            para atender às necessidades do mercado. Oferece prazo de entrega ágil, por meio de parcerias
                            com empresas de transportes.
                        </p>
                        <p style="margin-left: -12vw;">
                            Para mais informações, acesse: <a href="http://www.gimenessanches.com.br" target="_blanc">www.gimenessanches.com.br</a>
                        </p>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="fa fa-arrow-left fa-2x"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="fa fa-arrow-right fa-2x"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="col-md-12">

                <div class="col-md-12">
                    <div class="col-md-12 hidden" id="txtgimenes" >
                   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerymask")

    <script>
        workFree.mascararContato();
        $('#myCarousel').bind('slide.bs.carousel', function (e) {
            console.log('slide event!');
        });
    </script>
}

SiteWorkMotor/Views/WorkMotoPecas/Suporte.cshtml
@{
    ViewBag.Title = "Suporte";
    Layout = "../Shared/_LayoutDrMacete.cshtml";

}
<style>
    #livechat-full {
        left: 31% !important;
        width: 37% !important;
        height: 82% !important;
    }
</style>
<div class="row div-treinamento">
    <div class="col-md-6 col-md-offset-3">
        <h2>FICOU COM ALGUMA DÚVIDA?</h2>
        <hr/>
    </div>

    <div class="row">

        <div class="hidden" id="atualizador">
            <span>@ViewBag.Atualizador</span>
        </div>


        <div class="hidden" id="pat">
            <span>@ViewBag.tipoAcesso</span>
        </div>


        @if ((bool)ViewBag.Atualizador)
        {
            <div class="col-md-12">
                <h2>Atualizações</h2>
                <hr />
            </div>
            <div class="col-md-12">
                <h4>Última atualização do sistema realizada em @string.Format("{0:dd/MM/yyyy}", ViewBag.DataAtualizador), caso não tenha atualizado seu sistema clique <a href="/" target="_blanc" id="link-atualizador"> aqui</a> e baixe o atualizador.</h4>
            </div>
        }
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jquery")

    <script> 
        if($("#atualizador span").text() == 'True'){
            if($("#pat span").text() == 'dpk') {
                $("#link-atualizador").attr("href", "/DrMacete/baixarAtualizador/?descPatrocinador=dpk");
            }
            if ($("#pat span").text() == 'compredireto') {
                $("#link-atualizador").attr("href", "/DrMacete/baixarAtualizador/?descPatrocinador=compredireto");
            }
            if ($("#pat span").text() == 'gimenes') {
                $("#link-atualizador").attr("href", "/DrMacete/baixarAtualizador/?descPatrocinador=gimenes");
            }
        }
        $(document).ready(function () { // chat
            window.__lc = window.__lc || {};
            window.__lc.license = 5902661;
            (function () {
                var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
                lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
            })();
            setTimeout(function () {
                $("#livechat-compact-container").css("visibility", "hidden");
                $("#livechat-compact-container").css("opacity", "0");
                $("#livechat-compact-container").css("transform", "none");

                $("#livechat-full").css("visibility", "inherit");
                $("#livechat-full").css("opacity", "100");
                $("#livechat-full").css("transform", "none");
            }, 1500);
        });
    </script>
}

SiteWorkMotor/Views/WorkMotoPecas/Upgrade.cshtml
@model SiteWorkMotor.ViewModel.ClienteViewModel
@{
    ViewBag.Title = "Upgrade";
    Layout = "../Shared/_LayoutMotoPecas.cshtml";

}

<div class="row div-upgrade">
    <div class="col-md-12">
        <h2>Upgrade Workmotor Free</h2>
        <hr />
    </div>

    <div class="row">
        <div class="col-md-12">
            
            @if (!(bool)ViewBag.Registrar)
            {
                <div class="col-md-6 col-md-offset-3">
                    <div class="col-md-12">
                        <h4>Sua solicitação de upgrade foi registra, um representante comercial entrará em contato com você. Muito obrigada !</h4>
                    </div>
                </div>
            }
            else
            {
                <div class="col-md-6 col-md-offset-3">
                    <div class="col-md-12" id="sucessoCadastro" style="display: none;">
                        <h4>Sua solicitação de upgrade foi registra, um representante comercial entrará em contato com você. Muito obrigada !</h4>
                    </div>
                </div>

                <div class="col-md-8 col-md-offset-2 form-cliente">
                    @using (Html.BeginForm("RegistrarClienteUpgrade", "Home", FormMethod.Post, new {@id = "form-registrar-cliente-upgrade", @class = "form-horizontal", role = "form"}))
                    {
                        <div class="col-md-12">
                            <h4>Preencha os dados abaixo que entraremos em contato com você.</h4>
                        </div>

                        <div class="col-md-6 col-md-offset-3 erroProcesso hidden">
                            <h5>Erro no processo de solicitação de upgrade !</h5>
                        </div>

                        <div class="col-md-6 col-md-offset-3 validation-summary-errors">
                            @Html.ValidationSummary()
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.DropDownList("PatrocinadorId", (SelectList) ViewBag.Patrocinadores, "PATROCINADOR DO WORKMOTOR FREE", new {@class = "form-control dropdown-padrocinadores"})
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.TextBoxFor(m => m.CpfCnpj, new {@class = "form-control", @id = "cpfCnpj", @placeholder = "CPF/CNPJ"})
                            </div>
                            <div class="col-md-8" id="errorCpfCnpf"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.TextBoxFor(m => m.RazaoSocial, new {@class = "form-control", @placeholder = "NOME/RAZÃOSOCIAL"})
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.TextBoxFor(m => m.Email, new {@class = "form-control", @placeholder = "E-MAIL"})
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.TextBoxFor(m => m.Telefone, new {@class = "form-control", @id = "telefone", @placeholder = "TELEFONE"})
                            </div>
                            <div class="col-md-8" id="errorContato"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                @Html.TextBoxFor(m => m.Cep, new {@class = "form-control", @id = "cep", @placeholder = "CEP"})
                            </div>
                        </div>

                        <div class="col-md-2 col-md-offset-5">
                            <input type="submit" value="Confirmar" class="btn btn-primary"/>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

@section scripts{

    <script>
        workFree.mascararContato();
        workFree.mascararCpfCnpj();

        $(document).ready(function () {
            $("#cep").mask("99999-999");
        });

        $("#form-registrar-cliente-upgrade").submit(function (e) {
            e.preventDefault();

            if($(this).valid()) {
                $.ajax({
                    url: "/workmotopecas/RegistrarClienteUpgrade",
                    type: "post",
                    async: false,
                    data: $(this).serialize(),
                    success: function (data) {
                        if (data == "True") {
                            $("#form-registrar-cliente-upgrade").fadeOut(500, function () {
                                $("#sucessoCadastro").fadeIn(200);
                            });
                        } else {
                            $(".erroProcesso").removeClass("hidden");
                        }
                    }
                });
            }
            return false;
        });
    </script>
}