SiteWorkMotor/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Core.Core;
using SiteWorkMotor.Helper;
using SiteWorkMotor.ViewModel;

namespace SiteWorkMotor.Controllers
{
    public class BlogController : Controller
    {
        private readonly PostCore _postCore = new PostCore();

        [ValidateInput(false)]
        [Route("noticia/{id:int}/{descricao:string}")]
        public ActionResult Noticia(int id, string descricao)
        {
            var post = _postCore.PorId(id);
            return View("Noticia", new PublicacaoViewModel()
            {
                Id = post.Id,
                PalavrasChave = post.PALAVRASCHAVESPOSTS.Select(x => x.Descricao).ToList(),
                TextoPublicacao = PostFileHelper.RecuperarTextoPost(post.PathNoticia),
                TituloTexto = post.Titulo,
                Resumo = post.Resumo,
                PathMiniatura = post.PathMiniatura.Replace("\\", "/"),
                PublicadoEm = post.DataPublicacao ?? new DateTime()
            });
        }
        public ActionResult Noticias()
        {
            var posts = _postCore.Todos();

            foreach (var p in posts)
            {
                if (p.PathMiniatura != null)
                {
                    string path = p.PathMiniatura.Substring(p.PathMiniatura.LastIndexOf("\\Content"));
                    p.PathMiniatura = path;
                }
                
            }

            return View("Index", new PublicacoesViewModel()
            {
                Publicacao = posts.OrderByDescending(x => x.DataPublicacao).Select(PostHelper.ConverterPost).ToList(),
                PalavrasChave = PalavrasChavesMaisUsadas(posts.SelectMany(x => x.PALAVRASCHAVESPOSTS).Select(x => x.Descricao)),
            });
        }

        public ActionResult NoticiasPorPalavraChave(string palavra)
        {
            var posts = _postCore.PorPalavraChave(palavra);

            foreach (var p in posts)
            {
                if (p.PathMiniatura != null)
                {
                    string path = p.PathMiniatura.Substring(p.PathMiniatura.LastIndexOf("\\Content"));
                    p.PathMiniatura = path;
                }

            }

            return View("Index", new PublicacoesViewModel()
            {
                Publicacao = posts.OrderByDescending(x => x.DataPublicacao).Select(PostHelper.ConverterPost).ToList(),
                PalavrasChave = PalavrasChavesMaisUsadas(posts.SelectMany(x => x.PALAVRASCHAVESPOSTS).Select(x => x.Descricao))
            });
        }
        public ActionResult PesquisarNoticina(string palavra)
        {
            var posts = _postCore.PorPalavraChave(palavra);
            posts.AddRange(_postCore.ContainsDescricao(palavra));
            posts = posts.Distinct().ToList();

            foreach (var p in posts)
            {
                if (p.PathMiniatura != null)
                {
                    string path = p.PathMiniatura.Substring(p.PathMiniatura.LastIndexOf("\\Content"));
                    p.PathMiniatura = path;
                }

            }

            return View("Index", new PublicacoesViewModel()
            {
                Publicacao = posts.OrderByDescending(x => x.DataPublicacao).Select(PostHelper.ConverterPost).ToList(),
                PalavrasChave = PalavrasChavesMaisUsadas(posts.SelectMany(x => x.PALAVRASCHAVESPOSTS).Select(x => x.Descricao))
            });
        }

        private static List<string> PalavrasChavesMaisUsadas(IEnumerable<string> palavras)
        {
            return palavras.GroupBy(x => x).OrderByDescending(x => x.Count()).Take(5).Select(x => x.Key).ToList();

        }
    }
}

SiteWorkMotor/Views/Blog/Index.cshtml
@model SiteWorkMotor.ViewModel.PublicacoesViewModel
@{
    ViewBag.Title = "Edição";
    ViewBag.Href = "blog/noticias/";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}
<Br />
<Br />
<Br />
<div class="row">
    <div class="col-md-8">
        <h1 class="my-4">Notícias</h1>
        @if (Model.Publicacao.Count == 0)
        {
            <h3>Ainda não temos publicações disponíveis</h3>
        }
        @foreach (var post in Model.Publicacao)
        {
            <div class="row mt-4">
                <div class="col-md-4">
                    <img src="@post.PathMiniatura" style="max-width: 100%">
                    @*<img src="@Url.Content(post.PathMiniatura)">*@
                </div>
                <div class="card mb-4 col-md-8">
                    <div class="card-body">
                        <h2 class="card-title"><a href="@Url.Action("Noticia", "Blog", new {id = post.Id, Descricao = post.Url})" class="blog-link">@post.TituloTexto</a></h2>
                        <p class="card-text">@post.Resumo</p>
                        <a href="@Url.Action("Noticia", "Blog", new {id = post.Id, Descricao = post.Url})" class="btn btn-primary btn-azulClaro">LER MAIS &rarr;</a>
                    </div>
                    <div class="card-footer text-muted" style="padding-left: 15px; padding-right: 15px;">
                        Postado @post.PublicadoEm
                    </div>
                </div>
            </div>

        }


        @*<ul class="pagination justify-content-center mb-4">
            <li class="page-item">
                <a class="page-link" href="#">&larr; Voltar</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Próximo &rarr;</a>
            </li>
        </ul>*@
    </div>
    <div class="col-md-4" style="margin-top: -1rem;">
        <div class="card my-4">
            <form action="@Url.Action("PesquisarNoticina","Blog")">
                <h5 class="card-header">Pesquisar</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" name="palavra" id="palavra" placeholder="Pesquisar por...">
                        <span class="input-group-btn">
                            <button class="btn btn-primary btn-azulClaro" type="submit">PESQUISAR</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="card my-4">
            <h5 class="card-header">Em destaque</h5>
            <div class="card-body">
                <div class="row">
                    @*@{
                        var lista1 = new List<string>();
                        var lista2 = new List<string>();
                    }
                    @if (Model != null && Model.PalavrasChave.Any())
                    {
                        if (@Model.PalavrasChave.Count % 2 != 0)
                        {
                            Model.PalavrasChave.Add("");
                        }
                        try
                        {
                            lista1.AddRange(@Model.PalavrasChave.GetRange(0, (Model.PalavrasChave.Count / 2) - 1));
                            lista2.AddRange(@Model.PalavrasChave.GetRange((Model.PalavrasChave.Count / 2) - 1, @Model.PalavrasChave.Count - 1));
                        }
                        catch (Exception e)
                        {
                            lista1.AddRange(@Model.PalavrasChave.GetRange(0, (Model.PalavrasChave.Count) ));

                        }
                    }

                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">
                            @foreach (var palavra in lista1)
                            {
                                <li>
                                    <a href="@Url.Action("NoticiasPorPalavraChave","Blog")?palavra=@palavra">@palavra</a>
                                </li>
                            }
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">
                            @foreach (var palavra in lista2)
                            {
                                <li>
                                    <a href="@Url.Action("NoticiasPorPalavraChave","Blog")?palavra=@palavra">@palavra</a>
                                </li>
                            }
                        </ul>
                    </div>*@
                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">
                            @{ var counter = 0; }
                            @foreach (var palavra in Model.PalavrasChave)
                            {
                                counter++;
                                if (counter <= Math.Ceiling((double) Model.PalavrasChave.Count() / 2))
                                {
                                    <li>
                                        <a href="@Url.Action("NoticiasPorPalavraChave", "Blog")?palavra=@palavra">@palavra</a>
                                    </li>
                                }
                                else
                                {
                                    if (counter - 1 <= Math.Ceiling((double) Model.PalavrasChave.Count() / 2) && counter > Math.Ceiling((double)Model.PalavrasChave.Count() / 2))
                                    {
                                        @:</ul></div><div class="col-lg-6"><ul class="list-unstyled mb-0">
                                    }
                                    <li>
                                        <a href="@Url.Action("NoticiasPorPalavraChave", "Blog")?palavra=@palavra">@palavra</a>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

SiteWorkMotor/Views/Blog/Noticia.cshtml
@model  SiteWorkMotor.ViewModel.PublicacaoViewModel
@section MetaTags
{
    <meta property="fb:app_id"             content="2232115907016807">
    <meta property="og:url"                content="https://www.workmotor.com.br/Blog/Noticia/@Model.Id" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="@Model.TituloTexto" />
    <meta property="og:description"        content="@Model.Resumo" />
    <meta property="og:image:url"          content="https://www.workmotor.com.br/@Model.PathMiniatura.Substring(Model.PathMiniatura.LastIndexOf("Content"))" />
    <meta property="og:image:secure_url"   content="https://www.workmotor.com.br/@Model.PathMiniatura.Substring(Model.PathMiniatura.LastIndexOf("Content"))" />
    <meta property="og:image:width"        content="320" />
    <meta property="og:image:width"        content="240" />
    <meta property="og:site_name"          content="WorkMotor" />
}
@{
    ViewBag.Title = Model.TituloTexto;
    ViewBag.Href = "blog/noticia/" + Model.Id + "/";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}
<br />
<br />
<br />
<br />

@Styles.Render("~/Content/css")
<div class="col-md-12 blog-imagem">
    <a href="@Url.Action("Noticias", "Blog")"><i class="fa fa-arrow-left"></i><span> VER TODAS NOTÍCIAS</span></a>
    <div class="row">
        <div class="col-lg-8">
            <h1 class="mt-4"><b>@Model.TituloTexto</b>
            </h1>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <p><b>Publicado </b>@($"{@Model.PublicadoEm:F}")</p>
                </div>
                <div class="col-md-12 links-compartilhamento">
                    <b>COMPARTILHE: </b>
                    <a onclick="facebookShare()" href="javascript:void(0);" id="facebook" class="fa fa-facebook-square" ></a>
                    <a href="https://twitter.com/intent/tweet?url=https://www.workmotor.com.br/Blog/Noticia/@Model.Id;text=Vale%20a%20pena%20ver%20" class="fa fa-twitter-square" ></a>
                    <a href="https://wa.me/?text=https://www.workmotor.com.br/Blog/Noticia/@Model.Id" target="_blank" class="fa fa-whatsapp" ></a>
                    <a href="mailto:?subject=@Model.TituloTexto&body=https://www.workmotor.com.br/Blog/Noticia/@Model.Id" class="fa fa-envelope" style=""></a>
                </div>
            </div>
            <hr>
            @Html.Raw(Model.TextoPublicacao)
            <hr>
        </div>
        <div class="col-md-4" style="margin-top: -4rem;">
            <div class="card my-4">
                <form action="@Url.Action("PesquisarNoticina", "Blog")">
                    <h5 class="card-header">Pesquisar</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" name="palavra" id="palavra" placeholder="Pesquisar por...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary btn-azulClaro" type="submit">PESQUISAR</button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card my-4">
                <h5 class="card-header">Assuntos relacionados </h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                @{ var counter = 0; }
                                @foreach (var palavra in Model.PalavrasChave)
                                {
                                    counter++;
                                    if (counter <= Math.Ceiling((double) Model.PalavrasChave.Count() / 2))
                                    {
                                        <li>
                                            <a href="@Url.Action("NoticiasPorPalavraChave", "Blog")?palavra=@palavra">@palavra</a>
                                        </li>
                                    }
                                    else
                                    {
                                        if (counter - 1 <= Math.Ceiling((double) Model.PalavrasChave.Count() / 2) && counter > Math.Ceiling((double) Model.PalavrasChave.Count() / 2))
                                        {
                                            @:</ul></div><div class="col-lg-6"><ul class="list-unstyled mb-0">
                                        }
                                        <li>
                                            <a href="@Url.Action("NoticiasPorPalavraChave", "Blog")?palavra=@palavra">@palavra</a>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 links-compartilhamento">
        <p><b>COMPARTILHE: </b></p>
        <a onclick="facebookShare()" href="javascript:void(0);" id="facebook" class="fa fa-facebook-square"></a>
        <a href="https://twitter.com/intent/tweet?url=https://www.workmotor.com.br/Blog/Noticia/@Model.Id;text=Vale%20a%20pena%20ver%20" class="fa fa-twitter-square"></a>
        <a href="https://wa.me/?text=https://www.workmotor.com.br/Blog/Noticia/@Model.Id" target="_blank" class="fa fa-whatsapp"></a>
        <a href="mailto:?subject=@Model.TituloTexto&body=https://www.workmotor.com.br/Blog/Noticia/@Model.Id" class="fa fa-envelope" style=""></a>
    </div>
    <div class="col-md-6 links-compartilhamento">
        <p><b>VISITE NOSSO CANAL: </b></p>
        <a href="https://www.youtube.com/channel/UCu1qIzZARaQU2HXyFKfowgg" target="_blank" class="fa fa-youtube-play" ></a>
    </div>
</div>
<script>
    function facebookShare() {
        FB.ui({
            display: 'popup',
            method: 'share_open_graph',
            action_type: 'og.likes',
            action_properties: JSON.stringify({
                object:'https://www.workmotor.com.br/Blog/Noticia/@Model.Id',
            })
        }, function(response){});
    }
</script>